site_name: ISC2 Hawaii - CTF
theme:
    name: material
    font:
        text: Open Sans
    logo: assets/logo.png
    palette:
        - scheme: default
          primary: green
          accent: blue
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
        - scheme: slate
          primary: green
          accent: blue
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    features:
        - header.autohide
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
        - content.code.select
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.path
        - navigation.indexes
        #- navigation.footer
    language: en
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: Copyright &copy; 2023 ISC2 Hawaii - CTF Team
nav:
  - Home: index.md
  - Welcome (Read Me): introduction.md
  - CTF Resources: ctfresources.md